auction/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_upcoming, name='show_upcoming'),
    path('ended/', views.show_ended, name='show_ended'),
    path('add/', views.add, name='add_auction'),
    path('details/<int:pk>/', views.details, name='show_details'),
    path('buy/<int:pk>/', views.buy, name='buy_item'),
    path('search/<str:search_text>/', views.search_result, name='search_result')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from auction.views import show_upcoming
from django.http import HttpResponse


urlpatterns = [
    path('', show_upcoming, name='homepage'),
    path('health/', lambda request: HttpResponse('okay')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('auction/', include('auction.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('message/', views.message_view, name='message'),
    path('write/<int:pk>/', views.write_to, name='write_to')
]

auction/models.py
from django.db import models
from django.contrib.auth.models import User


class Auction(models.Model):
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=1024)
    image = models.ImageField(upload_to='images/')
    created_at = models.DateTimeField(auto_now=True)
    end_time = models.DateTimeField(null=True)
    seller = models.ForeignKey(User, related_name='seller', null=True, default=None, on_delete=models.CASCADE)

    # sell data
    sold = models.BooleanField(default=False)
    buyer = models.ForeignKey(User, null=True, default=None, related_name='buyer', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=6, null=True, decimal_places=2, default=0)


class Bid(models.Model):
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    amount = models.DecimalField(max_digits=6, decimal_places=2)

auction/forms.py
from django.forms import ModelForm
from .models import Auction, Bid


class AddAuctionForm(ModelForm):
    class Meta:
        model = Auction
        fields = ['title', 'description', 'image', 'price']


class BidForm(ModelForm):
    class Meta:
        model = Bid
        fields = ['amount']

auction/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from datetime import datetime, timezone
from .models import Auction, Bid
from .forms import AddAuctionForm, BidForm
from django.core.serializers import serialize
from django.contrib import messages
import pytz


def top_bid(auction):
    return auction.bid_set.all().order_by('-amount').first()


def unseen_wins(user):
    if not user.is_authenticated:
        return None
    return user.buyer.filter(end_time__lt=datetime.now(timezone.utc), sold=False).exclude(seller=user)


def seen_wins(user):
    return user.buyer.filter(end_time__lt=datetime.now(timezone.utc)).filter(sold=True)


def unread_messages(user):
    if not user.is_authenticated:
        return None
    return user.received_message.filter(seen=False).order_by('-sent_at')


def read_messages(user):
    if not user.is_authenticated:
        return None
    result = user.received_message.filter(seen=True) | user.sent_message.all()
    return result.order_by('-sent_at')


def get_unread_message_count(user):
    if not user.is_authenticated:
        return 0
    return len(unread_messages(user)) + len(unseen_wins(user))


def to_datetime(date, time):
    '''
    :param date: data extracted from datepicker input field
    :param time: data extracted from timepicker input field
    :return: python datetime object associated with given input, in UTC
    '''
    time = date + ' ' + time
    time = time.replace('/', ' ').replace(':', ' ')
    month, day, year, hour, minute = [int(item) for item in time.split()]
    return datetime(
        year=year,
        month=month,
        day=day,
        hour=hour,
        minute=minute,
        tzinfo=pytz.timezone('UTC')
    )


@login_required(login_url='/user/login/')
def add(request):
    if request.method == "POST":
        date = request.POST.get('datepicker', 'no date found')
        time = request.POST.get('timepicker', 'no time found')
        form  = AddAuctionForm(request.POST, request.FILES)

        try:
            auction = form.save()
            auction.seller = request.user
            auction.buyer = request.user
            auction.end_time = to_datetime(date, time)
            auction.save()
            messages.info(request, 'Item added.')
            return redirect('homepage')
        except Exception as e:
            messages.info(request, 'Some error occurred. Please try again.')

    context = {
        'message_cnt': get_unread_message_count(request.user)
    }
    return render(request, 'auction/add.html', context=context)


def details(request, pk):
    auction = get_object_or_404(Auction, pk=pk)

    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect('login')

        form = BidForm(request.POST)
        if form.is_valid():
            bid = Bid(
                auction=auction,
                bidder=request.user,
                amount=form.cleaned_data['amount']
            )
            if datetime.now(tz=timezone.utc) <= auction.end_time and bid.amount > auction.price:
                bid.save()

                auction.buyer = request.user
                auction.price = bid.amount
                auction.save()
                messages.info(request, 'Your bid was accepted!')
            else:
                messages.info(request, 'You must bid more than the last bid.')


    allow_bidding = (auction.seller != request.user)
    try:
        allow_buying = auction in unseen_wins(request.user)
    except Exception as e:
        allow_buying = False

    context = {
        'auction': auction,
        'bid_going_on': auction.end_time > datetime.now(timezone.utc),
        'allow_bidding': allow_bidding,
        'allow_buying': allow_buying,
        'user': request.user,
        'message_cnt': get_unread_message_count(request.user)
    }

    return render(request, 'auction/details.html', context=context)


def show_upcoming(request):
    auctions = Auction.objects.filter(
        end_time__gt=datetime.now(timezone.utc)
    )
    title = 'Active Listings'

    return show_all(request, title, auctions)


def show_ended(request):
    auctions = Auction.objects.filter(
        end_time__lte=datetime.now(timezone.utc)
    )
    title = 'Ended Listings'

    return show_all(request, title, auctions)


def show_all(request, title, auctions):
    if len(auctions) == 0:
        context = { 'auctions': None }
    else:
        context = { 'auctions': auctions }
    context['title'] = title
    context['message_cnt'] = get_unread_message_count(request.user)

    return render(request, 'auction/showall.html', context=context)


@login_required(login_url='/user/login/')
def buy(request, pk):
    auction = get_object_or_404(Auction, pk=pk)
    if auction in unseen_wins(request.user):
        auction.sold = True
        auction.save()

    return redirect('show_details', pk=pk)


def search_result(request, search_text):
    keywords = [word for word in search_text.split('+') if word]
    queryset = Auction.objects.filter(pk=-1)
    for keyword in keywords:
        queryset = queryset | Auction.objects.filter(title__icontains=keyword) | Auction.objects.filter(description__icontains=keyword)
    queryset = queryset.order_by('-created_at')

    response = serialize('json', queryset)
    return JsonResponse(response, safe=False)

templates/auction/add.html
{% extends 'base.html' %}

{% block head %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
{% endblock %}

{% block title %} Add Product for Auction {% endblock %}

{% block content %}
    <div class="container text-center">
        <div
            class="col-sm-12 col-md-8 col-lg-6 p-sm-1 p-md-2 p-lg-3 align-center mt-3"
            style="margin: auto;">
            <h1 class="display-5 mt-3">Add an item for auction</h1>
            <p class="mt-1">Please enter the following information</p>

            <!-- Add form -->
            <form action="{% url 'add_auction' %}"
                  method="post"
                  id="id_add_item_form"
                  enctype="multipart/form-data"
            >
                {% csrf_token %}

                <!-- Image upload -->
                <div class="form-group text-left mb-3">
                    <label for="id_image">Upload an Image of the Product</label>
                    <input type="file" name="image" accept="image/*" required id="id_image"
                            class="btn btn-md btn-block file-field" >
                </div>
                <!-- Image upload ends -->

                <!-- Title -->
                <div class="form-group text-left mb-3">
                    <label for="id_title">Title</label>
                    <input type="text"
                           name="title"
                           class="form-control"
                           maxlength="128"
                           placeholder="Product title"
                           required id="id_title"
                    >
                </div>
                <!-- Title input ends -->

                <!-- Description -->
                <div class="form-group text-left mb-3">
                    <label for="id_description">Description</label>
                    <input type="text" name="description" maxlength="1024" required
                            id="id_description"
                            class="form-control"
                            placeholder="Describe your product"
                    >
                </div>
                <!-- Description input ends -->

                <div class="form-group text-left mb-3">
                    <label for="id_price">Quote a Price: </label>
                    <input type="number" name="price" step="0.01" required id="id_price"
                           class="form-control" placeholder="0.01"
                    >
                </div>

                <!-- Date & Time Input begins here. -->
                <div class="form-group text-left mb-3">
                    <label for="datepicker">Auction End Time</label>
                    <div class="row">
                        <div class="col">
                            <input id="datepicker" name="datepicker" class="form-control"
                           placeholder="MM/DD/YYYY" required>
                        </div>
                        <div class="col">
                            <input id="timepicker" name="timepicker" class="form-control" required/>
                        </div>
                    </div>
                </div>
                <!-- Date & Time Input ends here. -->

                <!-- JavaScript code for Date & Time Input begins here. -->
                <script>
                    $('#datepicker').datepicker({
                        uiLibrary: 'bootstrap4'
                    });
                    $('#timepicker').timepicker({
                        uiLibrary: 'bootstrap4'
                    });
                </script>
                <!-- JavaScript code for Date & Time Input ends here. -->

                <!-- Submit button -->
                <button class="btn btn-block btn-primary" type="submit">
                    Add
                </button>
            </form>
            <!-- Login form ends -->
        </div>
    </div>
{% endblock %}

templates/auction/details.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1 class="display-3 text-center my-3">{{ auction.title }}</h1>
        <div class="row my-3">
            <div class="col col-sm-9 col-lg-6 mx-auto my-3">
                <img src="{{ auction.image.url }}"
                     alt="{{ auction.title }}"
                     class="img-fluid"
                     style="max-height: 480px;"
                >
            </div>

            <div class="col col-sm-9 col-lg-6 mx-auto my-3">
                <p><span class="font-weight-bold">Added by: </span>{{ auction.seller.first_name }}</p>
                <p><span class="font-weight-bold">Added at: </span>{{ auction.created_at }}</p>
                <p><span class="font-weight-bold">Expires at: </span>{{ auction.end_time }}</p>
                <p><span class="font-weight-bold">Details: </span>{{ auction.description }}</p>

                <p><span class="font-weight-bold">Current Quote: </span>{{ auction.price }}</p>

                {% if auction.seller != auction.buyer %}
                    <p><span class="font-weight-bold">Current Bidder: </span>{{ auction.buyer.first_name }}</p>
                {% else %}
                    <p><span class="font-weight-bold">Current Quote: </span>No quote yet.</p>
                    {% if allow_buying and bid_going_on %} <p>Be the first one to bid for this item!</p> {% endif %}
                {% endif %}

                {% if bid_going_on  %}
                    {% if allow_bidding %}
                        <form class="form-inline justify-content"
                              method="post"
                              action="{% url 'show_details' auction.pk %}"
                        >
                            {% csrf_token %}
                            <label class="my-1 mr-2" for="id_amount">Quote a Price: </label>
                            <input type="number" name="amount" step="0.01" required id="id_amount"
                                   class="my-1 mr-sm-2"
                            >
                            <button type="submit" class="btn btn-primary my-1">Submit</button>
                        </form>
                        <p>Need to know something? <a href="{% url 'write_to' auction.seller.pk %}">Contact Seller</a></p>
                    {% endif %}
                {% else %}
                    {% if auction.sold %}

                        {% if allow_buying %}
                            <p class="font-weight-bold">You have baught the item.</p>
                        {% else %}
                            <p class="font-weight-bold">The item is sold.</p>
                        {% endif %}

                    {% else %}

                        {% if auction.buyer == user %}
                            <p class="font-weight-bold">Congratulations! You won the bid!</p>
                            <a href="{% url 'buy_item' auction.pk %}" class="btn btn-block btn-success my-3">Buy the item!</a>
                            <p>Need to know something? <a href="{% url 'write_to' auction.seller.pk %}">Contact Seller</a></p>
                        {% endif %}
                    {% endif %}

                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}

templates/auction/showall.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}

{% block content %}

    <div class="container my-3">
        <form id="id_form" action="#" method="get">
            <div class="input-group">
                <input
                        id="id_search_text"
                        type="text"
                        class="form-control"
                        placeholder="Type your search query here"
                />
                <div class="input-group-prepend">
                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>

    <div class="cointainer" id="results">
        <div class="row my-3">
            {% for auction in auctions %}
                <div class="col col-sm col-md-6 col-lg-3 my-3 mx-3">
                    <div class="card" style="width: 18rem;">
                        <img src="{{ auction.image.url }}" class="card-img-top" height="300px" alt="{{ auction.title }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ auction.title }}</h5>
                            <p>{{ auction.description }}</p>
                            {% if auction.sold %}
                                <p><span class="font-weight-bold">Sold for: </span>{{ auction.price }}</p>
                            {% elif auction.price %}
                                <p><span class="font-weight-bold">Current bid: </span>{{ auction.price }}</p>
                            {% else %}
                                <p><span class="font-weight-bold">Current bid: </span>No bid yet.</p>
                            {% endif %}

                            <a href="/auction/details/{{ auction.pk }}/" class="btn btn-primary btn-block">View Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
{% endblock %}

{% block script %}
        <script>

        document.getElementById("id_form").addEventListener("submit", event => {
            let searchText = document.getElementById("id_search_text").value;
            searchText = searchText
                .replace(/([^0-9a-z])/gi, " ")
                .split(" ")
                .join("+");

            const url = `http://${window.location.host}/auction/search/${searchText}`;

            let resultElement = document.getElementById('results');
            console.log(resultElement);
            let newHtml = `
            <div class="cointainer my-3" id="results">
                <div class="row my-3">`;

            try {
                fetch(url).then(res => res.json())
                    .then(res => {

                        if (JSON.parse(res).length === 0) {
                            resultElement.innerHTML = `
                                <div class="cointainer" id="result">
                                    <br><br><br>
                                    <p class="font-weight-bold text-content-center">
                                        Ops! Could not find any match for your searched keywords! Try some other keyword instead?
                                    </p>
                                    <br><br><br>
                                </div>
                            `;
                            return;
                        }

                        for (let a of JSON.parse(res)) {
                            newHtml += `
                                        <div class="col col-sm col-md-6 col-lg-3 my-3 mx-3" id="result">
                                            <div class="card" style="width: 18rem;">
                                                <img src="http://${window.location.host}/media/${a.fields.image}" class="card-img-top" alt="${a.fields.title}" height="300px" />
                                                <div class="card-body">
                                                    <h5 class="card-title">${a.fields.title}</h5>
                                                    <p>${a.fields.description}</p>`;
                            if (a.fields.sold) {
                                newHtml += `<p> <span class="font-weight-bold">Sold for: </span>${a.fields.price} </p>`;
                            } else if (a.fields.price) {
                                newHtml += `<p> <span class="font-weight-bold">Current bid: </span>${a.fields.price} </p>`;
                            } else {
                                newHtml += `<p><span class="font-weight-bold">Current bid: </span>No bid yet. </p>`;
                            }
                            newHtml +=              `<a href="/auction/details/${a.fields.pk}/" class="btn btn-primary btn-block">View Details</a>
                                                </div>
                                            </div>
                                        </div>`;
                        }

                        newHtml += `
                                    </div>
                                </div>`;

                        resultElement.innerHTML = newHtml;
                    }).catch(error => {
                        resultElement.innerHTML = `
                                <div class="cointainer">
                                    <br><br><br>
                                    <p class="font-weight-bold text-content-center">
                                        Couldn't get response from the server.
                                    </p>
                                    <br><br><br>
                                </div>
               `;
                });
            } catch (e) {
            }

            event.preventDefault();
        });

    </script>
{% endblock %}