project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from auction.views import show_upcoming
from django.http import HttpResponse


urlpatterns = [
    path('', show_upcoming, name='homepage'),
    path('health/', lambda request: HttpResponse('okay')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('auction/', include('auction.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('message/', views.message_view, name='message'),
    path('write/<int:pk>/', views.write_to, name='write_to')
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Message(models.Model):
    sender = models.ForeignKey(User, null=True, default=None, related_name='sent_message', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, null=True, default=None, related_name='received_message', on_delete=models.CASCADE)
    message = models.TextField(max_length=1024)
    seen = models.BooleanField(default=False)
    sent_at = models.DateTimeField(auto_now=True)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthday = models.DateField(auto_now=False, blank=True, null=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

user/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Message


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email', 'password')


class DateForm(forms.Form):
    datepicker = forms.DateField()


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['message']

user/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from .forms import RegistrationForm, DateForm, MessageForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Message
from itertools import chain
from auction.views import (
    read_messages,
    unread_messages,
    seen_wins,
    unseen_wins,
    get_unread_message_count
)



def register_view(request):
    # a user should not be able to register for a new account while being logged in
    if request.user.is_authenticated:
        return HttpResponse("First logout")

    if request.method == "POST":

        date_form = DateForm(request.POST)
        if not date_form.is_valid():
            messages.info(request, "Please enter a valid date.")
            return render(request, 'user/register.html', context={'user': request.user})

        # checking whether the passwords match
        password1 = request.POST.get('password1', '')
        password2 = request.POST.get('password2', '')
        if password1 != password2:
            messages.info(request, "Your passwords don't match.")
            return render(request, 'user/register.html', context={'user': request.user})

        data = {
            'username':request.POST.get('email', ''),
            'first_name': request.POST.get('name', ''),
            'email': request.POST.get('email', ''),
            'password': password1
        }

        form = RegistrationForm(data)
        if form.is_valid():
            user = form.save()
            user.set_password(request.POST.get('password1', ''))
            user.profile.birthday = date_form.cleaned_data['datepicker']
            print(date_form.cleaned_data['datepicker'])
            user.save()
            print(user.profile.birthday)

            login(request, user)
            return redirect('homepage')
        else:
            messages.info(request, "The email is already registered. Please login or reset password.")
            context = {
                'user': request.user
            }
            render(request, 'user/login.html')

    return render(request, 'user/register.html', context={'user': request.user})


def login_view(request):
    if request.method == "POST":
        email = request.POST.get('email', '')
        password = request.POST.get('password', '')
        user = authenticate(username=email, password=password)
        if user:
            login(request, user)
        else:
            messages.info(request, "The email/password is not correct. Please try again.")

    if request.user.is_authenticated:
        return redirect('homepage')
    return render(request, 'user/login.html', context={'user': request.user})


@login_required
def logout_view(request):
    logout(request)
    return redirect('login')


@login_required(login_url='/user/login/')
def message_view(request):
    user = request.user
    context = {
        'seen_wins': seen_wins(user),
        'unseen_wins': unseen_wins(user),
        'unseen_wins_len': len(unseen_wins(user)),
        'unread_messages': unread_messages(user),
        'unread_messages_len': len(unread_messages(user)),
        'read_messages': read_messages(user),
        'message_cnt': get_unread_message_count(request.user)
    }

    return render(request, 'user/read_message.html', context=context)


@login_required(login_url='/user/login/')
def write_to(request, pk):
    sender = request.user
    receiver = get_object_or_404(User, pk=pk)

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            Message(
                message=form.cleaned_data['message'],
                sender=sender,
                receiver=receiver
            ).save()

    messages_to = Message.objects.filter(sender=sender, receiver=receiver)
    messages_from = Message.objects.filter(sender=receiver, receiver=sender)
    for message in unread_messages(sender):
        message.seen = True
        message.save()

    messages = sorted(
        chain(messages_to, messages_from),
        key=lambda instance: instance.sent_at
    )
    context = {
        'user': sender,
        'to_user': receiver,
        'all_messages': messages,
        'message_cnt': get_unread_message_count(sender)
    }

    return render(request, 'user/message_with.html', context=context)

templates/user/login.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %}
{% block content %}
    <div class="container text-center">
        <div
            class="col-sm-12 col-md-8 col-lg-6 p-sm-1 p-md-2 p-lg-3 align-center mt-3"
            style="margin: auto;">
            <h1 class="display-5 mt-3">Login to your account!</h1>
            <p class="mt-1">Please enter the following information</p>

            <!-- Login form -->
            <form action="{% url 'login'%}" method="post" id="id_login-form">
                {% csrf_token %}

                <!-- Email input -->
                <div class="form-group text-left mb-3">
                    <label for="id_email">Email address</label>
                    <input
                        id="id_email"
                        name="email"
                        class="form-control"
                        type="email"
                        placeholder="email@example.com"
                        required
                    />
                </div>
                <!-- Email input ends -->

                <!-- Password input -->
                <div class="form-group text-left mb-3">
                    <label for="id_password">Password</label>
                    <input
                        id="id_password"
                        name="password"
                        class="form-control"
                        type="password"
                        placeholder="****************"
                        required
                    />
                </div>
                <!-- Password input ends -->

                <!-- Submit button -->
                <button class="btn btn-block btn-primary" type="submit">
                    Login
                </button>
            </form>
            <!-- Login form ends -->

            <p class="mute my-3">Don't have an account? <a href="{% url 'register' %}">Register here</a></p>
        </div>
    </div>
{% endblock %}

templates/user/message_with.html
{% extends 'base.html' %}
{% block title %} Message {% endblock %}
{% block content %}
    <div class="container my-3">
        <p class="font-weight-bold">Your Messages with {{ to_user.first_name }}</p>
        <ul>
            {% for message in all_messages %}
                <li><span class="font-weight-bold">{{ message.sender.first_name }} at {{ message.sent_at }}:</span>
                    at {{ message.message }}</li>
            {% endfor %}
        </ul>
        <p class="font-weight-bold">Send a new message:</p>
        <form class="form-group justify-content"
              method="post"
              action="#"
        >
            {% csrf_token %}
            <textarea name="message" rows="2" maxlength="1024" required id="id_message"
                      class="form-control"
            ></textarea>
            <button type="submit" class="btn btn-primary btn-block my-3">Submit</button>
        </form>
    </div>
{% endblock %}

templates/user/read_message.html
{% extends 'base.html' %}
{% block title %} Messages {% endblock %}

{% block content %}

    <div class="container my-3">
        {% if unseen_wins %}
            <p class="font-weight-bold">You have {{ unseen_wins_len }} unread notifications</p>
            <ol>
                {% for auction in unseen_wins %}
                    <li>Congratulations! You have won bid for {{ auction.title }}!
                        <a href="{% url 'show_details' auction.pk %}">Buy item</a>
                    </li>
                {% endfor %}
            </ol>
        {% endif %}

        {% if seen_wins %}
            <p class="font-weight-bold">Older system messages:</p>
            <ol>
                {% for auction in seen_wins %}
                    <li>Congratulations! You have won bid for {{ auction.title }}!
                        <a href="{% url 'show_details' auction.pk %}">See details</a>
                    </li>
                {% endfor %}
            </ol>
        {% endif %}

        {% if unread_messages %}
            <p class="font-weight-bold">Unread messages:</p>
            <ol>
                {% for message in unread_messages %}
                    <li> <span class="font-weight-bold">{{ message.sender.first_name }} at {{ message.sent_at }}:</span>
                        {{ message.message }} <a href="{% url 'write_to' message.sender.pk %}">View Conversation</a>
                {% endfor %}
            </ol>
        {% endif %}

        {% if read_messages %}
            <p class="font-weight-bold">Older messages:</p>
            <ol>
                {% for message in read_messages %}
                    <li> <span class="font-weight-bold">{{ message.sender.first_name }} at {{ message.sent_at }}:</span>
                        {{ message.message }} <a href="{% url 'write_to' message.sender.pk %}">View Conversation</a>
                {% endfor %}
            </ol>
        {% endif %}

    </div>

{% endblock %}

templates/user/register.html
{% extends 'base.html' %}

{% block head %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block title %} Register {% endblock %}

{% block content %}
    <div class="container text-center col-sm-12 col-md-8 col-lg-6 align-center"
         style="margin: auto">

        <h1 class="display-5 mt-3">Register for free!</h1>
        <p class="mt-1">Please enter the following information</p>

        <!-- Registration form -->
        <form action="{% url 'register'%}" method="post" id="register-form">
        {% csrf_token %}

            <!-- Full name input -->
            <div class="form-group text-left mb-3">
                <label for="name">Full Name</label>
                <input id="name" name="name" class="form-control" type="text"
                   placeholder="John Doe" minlength="8" maxlength="32" required>
            </div>

            <!-- Email input -->
            <div class="form-group text-left mb-3">
                <label for="email">Email</label>
                <input id="email" name="email" class="form-control" type="email"
                       placeholder="email@example.com" required>
            </div>

            <!-- Password input -->
            <div class="form-group text-left mb-3">
                <label for="password1">Password</label>
                <input id="password1" name="password1" class="form-control" type="password"
                       placeholder="****************"  minlength="8" maxlength="32" required>
            </div>


            <!-- Password confirmation input -->
            <div class="form-group text-left mb-3">
                <label for="password2">Confirm Password</label>
                <input id="password2" name="password2" class="form-control" type="password"
                       placeholder="****************" minlength="8" maxlength="32" required>
            </div>

            <!-- Date Input begins here. -->
           <!--input id="datepicker" width="276" /-->
            <div class="form-group text-left mb-3">
                <label for="datepicker">Birthday</label>
                <input id="datepicker" name="datepicker"
                       placeholder="MM/DD/YYYY" required>
            </div>

            <script>
                $('#datepicker').datepicker({
                    uiLibrary: 'bootstrap4'
                });
            </script>

            <!-- Submit button -->
            <button class="btn btn-block btn-primary" type="submit">Register</button>
        </form>

        <p class="mute my-3">Already have an account? <a href="{% url 'login' %}">Login here</a></p>
    </div>

{% endblock %}